apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-app.fullname" . }}-frontend
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      nodePort: 30030
  selector:
    {{- include "todo-app.selectorLabels" . | nindent 4 }}
    app: frontend